### ISSUE TITLE
cross-referencing with cleveref

### ISSUE THREAD

**Issue by malindasds** [pjb7687/uni-hd-phd-thesis-latex-template#1]
Hi, I was trying to use your template to write my thesis. I wanted to use cross-referencing via the cleveref package, but it shows ?? in the place of the cross-references. 

\usepackage{cleveref}

In section \cref{section} we discuss about something. 

\section{section}
\label{section}
This is a sentense. 

OUTPUT: 
In section **??** we discuss about something. 

There is something within the class file that is interfering, but I can't figure out what. 

I prefer to use cleveref rather than \ref as it mentions the type of reference (eg: section, figure, table), so the question.

**Comment by pjb7687** [comment]
Hi, It seems like the package `cleveref` depends on another package `hyperref`, which needs to be loaded **before** `cleveref`. So, add another line above `\usepackage{cleveref}`:

```tex
\usepackage{hyperref}
\usepackage{cleveref}
```

I also tested this on Overleaf, it seems to work well.

**Comment by malindasds** [comment]
God I'm stupid! Thanks a lot!
